# Generated by Django 4.1.4 on 2023-04-01 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='kullanici ismi')),
                ('join_date', models.DateTimeField(verbose_name='katilim tarihi')),
                ('pr_image', models.FileField(upload_to=None, verbose_name='profil resmi')),
                ('bio', models.TextField(max_length=150, verbose_name='kullanici hakkinda')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='kullanici')),
            ],
        ),
    ]
