# Generated by Django 4.1.4 on 2023-04-01 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='kategori ismi')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ev ismi')),
                ('image', models.FileField(null=True, upload_to=None, verbose_name='ev gorseli')),
                ('country', models.CharField(max_length=50, verbose_name='ulke')),
                ('location', models.TextField(max_length=100, verbose_name='konum')),
                ('publish_date', models.DateTimeField(verbose_name='yayin tarihi')),
                ('price', models.IntegerField(verbose_name='ucret')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.category', verbose_name='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
    ]
