# Generated by Django 4.1.4 on 2023-04-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_alter_house_category_alter_house_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='yorum yapan')),
                ('text', models.TextField(max_length=150, verbose_name='yorum')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.house', verbose_name='ev')),
            ],
        ),
    ]
