# Generated by Django 4.1.4 on 2023-04-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_remove_comment_name_alter_comment_commenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image1',
            field=models.FileField(null=True, upload_to=None, verbose_name='ev gorseli1'),
        ),
        migrations.AddField(
            model_name='house',
            name='image2',
            field=models.FileField(null=True, upload_to=None, verbose_name='ev gorseli2'),
        ),
        migrations.AddField(
            model_name='house',
            name='image3',
            field=models.FileField(null=True, upload_to=None, verbose_name='ev gorseli3'),
        ),
        migrations.AddField(
            model_name='house',
            name='image4',
            field=models.FileField(null=True, upload_to=None, verbose_name='ev gorseli4'),
        ),
    ]
