# Generated by Django 4.1.4 on 2023-04-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_house_image1_house_image2_house_image3_house_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='c_image',
            field=models.FileField(null=True, upload_to=None, verbose_name='kategori iconu'),
        ),
    ]
